const ERROR_CODE_INCORRECT_DATA = 400;
const ERROR_CODE_DATA_NOT_FOUND = 404;
const ERROR_CODE_DEFAULT = 500;

module.exports = {
  ERROR_CODE_INCORRECT_DATA,
  ERROR_CODE_DATA_NOT_FOUND,
  ERROR_CODE_DEFAULT,
};
